// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCuDscJxNpT_42yOgZmhWbAdbj5V2Nsc',
    appId: '1:954786387750:web:d68c2799e935230ce393e7',
    messagingSenderId: '954786387750',
    projectId: 'fluuter-login-app-311b1',
    authDomain: 'fluuter-login-app-311b1.firebaseapp.com',
    storageBucket: 'fluuter-login-app-311b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcUUCf_rw1MhXwfeyqTAOluZ31_2JmjE',
    appId: '1:954786387750:android:24065b5f779b5827e393e7',
    messagingSenderId: '954786387750',
    projectId: 'fluuter-login-app-311b1',
    storageBucket: 'fluuter-login-app-311b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3c9M7Obnr0aOHWPYLXzClJdySXV_KLxY',
    appId: '1:954786387750:ios:78414f73f08e4924e393e7',
    messagingSenderId: '954786387750',
    projectId: 'fluuter-login-app-311b1',
    storageBucket: 'fluuter-login-app-311b1.appspot.com',
    androidClientId: '954786387750-0ncni47cjsshefsrk2nmhvfc6v6ld4jp.apps.googleusercontent.com',
    iosClientId: '954786387750-5k9t4jsggb37kss43u24b0bf5sl0f1os.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );
}
